server:
  port: 8080

spring:
  application:
    name: app-vault-client


  datasource:
    url: jdbc:postgresql://postgres_task_vault_approle:5432/postgres_task_vault_approle
#    url: jdbc:postgresql://localhost:15432/postgres_task_vault_approle
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  config:
    import: vault://

  cloud:
    vault:
      enabled: true
      scheme: http
      host: vault_prod_approle
      port: 8200
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: postgres