#server:
#  port: 8080
#
#spring:
#  application:
#    name: hashicorp-vault
#
#  datasource:
#    url: jdbc:postgresql://localhost:15432/postgres_task_vault
#    driverClassName: org.postgresql.Driver
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#
#  config:
#    import: vault://
#  cloud:
#    vault:
#      enabled: true
#      uri: http://localhost:8200
#      token: root
#      kv:
#        default-context: postgres


server:
  port: 8080

spring:
  application:
    name: hashicorp-vault
  profiles:
    active: secret

  datasource:
    url: jdbc:postgresql://postgres_task_vault:5432/postgres_task_vault
#    url: jdbc:postgresql://localhost:15432/postgres_task_vault
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  config:
    import: vault://
  cloud:
    vault:
      enabled: true
      scheme: http
      host: vault_prod
      port: 8200
#      uri: http://localhost:8200
      token: ${VAULT_TOKEN}
      kv:
        default-context: postgres
        backend: secret
