services:

  vault_app:
#    image: vault_app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vault_app
    env_file:
      - .env
    networks:
      - vault_networks
    ports:
      - "8080:8080"
    depends_on:
      - vault_prod


  vault_prod:
    image: hashicorp/vault:1.19.4
    container_name: vault_prod
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/file
      - ./vault/config:/vault/config
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault_networks


  postgres_task_vault:
    image: postgres:latest
    container_name: postgres_task_vault
    environment:
      POSTGRES_DB: postgres_task_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - type: volume
        source: postgres_task_vault
        target: /var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - vault_networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  vault_networks:

volumes:
  postgres_task_vault:
  vault-data:

#  vault:
#    image: hashicorp/vault:1.19.4
#    container_name: vault
#    ports:
#      - "8200:8200"
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: root
#      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - vault-data:/vault/file
#    command: vault server -dev
#    networks:
#      - vault_networks

#  vault operator init
#
#  / # vault operator init
#Unseal Key 1:
#Unseal Key 2:
#Unseal Key 3:
#Unseal Key 4:
#Unseal Key 5:
#
#Initial Root Token:
#
#  Vault initialized with 5 key shares and a key threshold of 3. Please securely
#  distribute the key shares printed above. When the Vault is re-sealed,
#  restarted, or stopped, you must supply at least 3 of these keys to unseal it
#  before it can start servicing requests.
#
#  Vault does not store the generated root key. Without at least 3 keys to
#  reconstruct the root key, Vault will remain permanently sealed!
#
#  It is possible to generate new unseal keys, provided you have a quorum of
#  existing unseal keys shares. See "vault operator rekey" for more information.
#  / #
#
#  vault operator unseal yd1HVx+zneZjOm8pBA9Kkkm2qu+4CtO6Z31QosWW+rPR